### PR TITLE
align astor's results hierarchy on nopol's results hierarchy

### PR DESCRIPTION
**Pull request by danglotb**
changes:
* renamed all subfolder project in lowercase
* remove the prefix seed of results for each seed
* change key in json bugExposingTest by BugExposingTest
* remove subfolder "generatedTests" of seed folder

The global layout of path is now results/{tool}/{project}/{bugID}/{seed}/{packages/EvoSuiteTest}

### CODE REVIEW

**Comment by monperrus** [comment]
change scripts accordingly

**Comment by danglotb** [comment]
I updated scripts, and use pretty print for json file: One issue is that is reorder the output.

But the content is the same. I did not updated json files in this PR

**Comment by monperrus** [comment]
ready to merge?

**Comment by danglotb** [comment]
yes it is.

**Pull request merged**
