### PR TITLE
add fixed EvoSuite test for astor/jGenProg

### PR DESCRIPTION
**Pull request by danglotb**

### CODE REVIEW

**Comment by monperrus** [comment]
can you remove the evosuitelog.txt from the commit? (not from the repo :-) thanks

**Comment by monperrus** [comment]
ready to merge?

**Comment by danglotb** [comment]
yes, i removed evosuitelog.txt

**Comment by monperrus** [comment]
are the json files (chart.json) a copy of the other ones? if yes, they should be removed, if no, what are the differences?

**Comment by danglotb** [comment]
No, they are not same files.

Those json files are reports of AsserFixer, for each project, for each bug id and for each seed, for each bug exposing tests, describing:

- the name
- if the adaptation succeed
- remaining failures (if adaptation succeed, it is empty)
- if the bug exposing test pass (before adaptation)
- if the adaptation could not be done due to time out.

maybe we should rename them.

**Comment by monperrus** [comment]
> maybe we should rename them.

yes, to avoid confusion, like `Chart50-AssertFixer.json`

**Comment by danglotb** [comment]
I renamed files. I also renamed Nopol's files with the same convention.

**Pull request merged**
