### PR TITLE
Updating json files

### PR DESCRIPTION
**Pull request by martinezmatias**
The PR commits an update to the results.json files. I remove from those files the patches that we dont study in this work, remove properties that we dont analyze and rename some properties with ugly names. I commit the scripts from creating the new json files from the logs + two test cases. 
Moreover, I commit some changes in the script structure.

### CODE REVIEW

**Comment by monperrus** [comment]
Excellent. Where are the scripts?

**Comment by martinezmatias** [comment]
Script introduced in commit 
https://github.com/Spirals-Team/test4repair-experiments/pull/3/commits/5fdc4fa01d82d6ced0ea6a3e61b1447e35035a76

For instance, the log parser is:
https://github.com/Spirals-Team/test4repair-experiments/pull/3/commits/5fdc4fa01d82d6ced0ea6a3e61b1447e35035a76#diff-d7aaaced77de026292f720ddc81a4c9d

**Comment by monperrus** [comment]
OMG!  Files changed: 1,033  :-)

where are the files produced by those scripts?

**Comment by martinezmatias** [comment]
The updated json files are in the same location they were before the commit:  [fe501ae](https://github.com/Spirals-Team/test4repair-experiments/pull/3/commits/fe501ae6f943a633dd94fd33f9891833f6290891), that is folder: 
 https://github.com/Spirals-Team/test4repair-experiments/tree/master/results/jGenProg%2BMinImpact/Patches%20and%20Analysis
In that folder, 755 json files were changed.

Then, I commit the movement of one folder with Astor scripts

**Pull request merged**
