### PR TITLE
Moving Scripts and data to new folders

### PR DESCRIPTION
**Pull request by martinezmatias**
Two commits: 
One with the scripts for classifying patches (A, B overfitting) from JSON files (ie. json generated by astor, AND json with the BET information). The classifier does not run any test nor patched version, only analyze logs.
Includes test cases for testing classification of Math_50 patches for all seeds.

Second commit: Results in JSON file

### CODE REVIEW

**Comment by monperrus** [comment]
Hi Matias,
Two comments:

*  scripts/pythonScript/data/ -> don't put a data folder in folder script, data should be in "results"
* scripts/pythonScript/data/datajsonbet -> don't duplicate the JSON file, it's confusing; It's better to replace the existing ones.

**Comment by martinezmatias** [comment]
Hi Martin
The out data that generates this script (introduced by commit 4c13c7a) is actually in the result folder:  
results/jGenProg+MinImpact/patch_classification/patchOverfittingClassification.json

The files inside "data/" folder (JSON) are used only for the test script.  We can point directly to the result folder and remove this data folder, or alternativelly rename "data" to "testdata"

**Comment by monperrus** [comment]
rename data/databejson -> test-resources
remove readme file

**Comment by monperrus** [comment]
and rebase

**Comment by monperrus** [comment]
@martinezmatias would be great to finsih this one and merge before it's becomes unmergable

**Comment by martinezmatias** [comment]
@monperrus updated dir names

**Comment by monperrus** [comment]
awesome! would be great to set up travis here to do some sanity checks

**Pull request merged**
